# Generated by Django 2.2.7 on 2019-11-09 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='created_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_by',
            new_name='guest_user',
        ),
    ]
